### PR TITLE
Add actix multipart support

### LINKED ISSUE #13: Add support for actix-multipart
Currently one cannot use [actix-multipart](https://docs.rs/actix-multipart/latest/actix_multipart/) together with this crate, since there is no `CsrfGuard` implementation on `actix-multipart`'s [`MultipartForm`](https://docs.rs/actix-multipart/latest/actix_multipart/form/struct.MultipartForm.html) extractor. It would be quite nice to be able to do this.

this would require #12 as a prerequisite due to an ahash version incompatibility.

### PR DESCRIPTION
**Pull request by ghost**
This PR adds support for `actix-multipart`'s MultipartForm , documentation for the feature and additional tests to cover the feature. I also made sure to tell docs.rs to build the documentation with all features at all times.  

I also added a list of features (currently it's just `actix-multipart`) to make sure all users know what features this crate has and what they do. Something I sadly don't see often enough.

fixes #13

### CODE REVIEW

**Comment by ghost** [comment]
AH yeah okay it seems my local install defaulted to 1.82, lemme have a look if i can fix this without updating the MSRV again

**Comment by ghost** [comment]
seems `parse-size@1.0.0` works with 1.72  and `actix-multipart`, so it doesn't seem like there will be an issue downgrading it.

File: Cargo.toml [hunk 1]
```diff
@@ -11,13 +11,20 @@ keywords = ["actix", "middleware", "csrf"]
...
+
 [dependencies]
 actix-web = { version = "4.3.1", default-features = false, features = [ "cookies" ] }
 base64 = { version = "0.21.0", default-features = false, features = [ "std" ]}
 cookie = "0.16"
 rand = { version = "0.8", features = [ "std_rng" ] }
 tracing = "0.1"
 serde = { version = "1", default-features = false }
+actix-multipart = { version = "0.7.2" , optional = true }
+parse-size = "=1.0.0"
```
Comment (edward-shen) [inline Cargo.toml]: Where is this dependency needed?

File: src/lib.rs [hunk 2]
```diff
@@ -99,6 +103,42 @@
...
+//!
+//! Usage with [`actix_multipart`] is almost the same as using it with
+//! actix's buiiltin [`Form`](actix_web::web::Form), with one exception:
+//! the `csrf_token` field must have type [`Text<CsrfToken>`](actix_multipart::form::text::Text)
+//! to interpret the CSRF token from the
+//! multipart form data. This works as follows:
+//!```
+//! # use actix_web::{HttpResponse, Responder, post};
+//! use actix_multipart::form::{text::Text, MultipartForm};
+//! use actix_csrf::extractor::{Csrf, CsrfGuarded, CsrfToken};
```
Comment (edward-shen) [inline src/lib.rs]: this doctest is failing:
```

---- src/lib.rs - (line 118) stdout ----
error[E0433]: failed to resolve: use of undeclared crate or module `actix_multipart`
 --> src/lib.rs:121:6
  |
6 |  use actix_multipart::form::{text::Text, MultipartForm};
  |      ^^^^^^^^^^^^^^^ use of undeclared crate or module `actix_multipart`

error[E0277]: the trait bound `fn(Csrf<{type error}>) -> impl std::future::Future<Output = impl Responder> {login}: Handler<_>` is not satisfied
   --> src/lib.rs:134:11
    |
18  |  #[post("/login")]
    |  ----------------- required by a bound introduced by this call
19  |  async fn login(form: Csrf<MultipartForm<LoginForm>>) -> impl Responder {
    |           ^^^^^ the trait `Handler<_>` is not implemented for fn item `fn(Csrf<{type error}>) -> impl std::future::Future<Output = impl Responder> {login}`
    |
note: required by a bound in `Resource::<T>::to`
   --> /home/edward/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-web-4.3.1/src/resource.rs:240:12
    |
238 |     pub fn to<F, Args>(mut self, handler: F) -> Self
    |            -- required by a bound in this associated function
239 |     where
240 |         F: Handler<Args>,
    |            ^^^^^^^^^^^^^ required by this bound in `Resource::<T>::to`

error: aborting due to 2 previous errors
```

This is not being caught at ci because `cargo test` there is invoked with `--all-features`. We probably want another `run:` line for just a test run without any features?

Comment (edward-shen) [reply src/lib.rs]: Looks like we need to `cfg_attr` this block of documentation: https://users.rust-lang.org/t/doctests-that-require-a-non-default-feature-is-it-possible/29529

Or make this a default dependency. I think I prefer making the docs a little messier if it means keeping our deps light.

**Comment by edward-shen** [comment]
Looks good! Left a few comments, let me know what you think.

Depending if you have time and you'd like this to be a more prominent feature, you could also add an example in the `examples/` folder. Not required, ofc.

**Comment by ghost** [comment]
> Looks good! Left a few comments, let me know what you think.

I don't think you sctually submitted the comments with your review, cuz I can't see them. The buttons for this are at the top right of the "Files changed" tab, where you can choose "Approve", "Comment" and "Request Changes"

> Depending if you have time and you'd like this to be a more prominent feature, you could also add an example in the `examples/` folder. Not required, ofc.

Oh yeah that seems like a great Idea. Shouldn't be too hard to do ^^

**Comment by edward-shen** [comment]
Oops, sorry! It's been a while since I've used GitHub for code review.

File: src/lib.rs (hunk 2 above)
Comment (ghost) [reply src/lib.rs]: Oh yeah I kinda forgot about that. I usually don't like doing that because it makes the docs hard to read inline, but you're right in that it makes more sense to do so.

File: Cargo.toml (hunk 1 above)
Comment (ghost) [reply Cargo.toml]: It seems that it is a transitive dependency of `actix-multipart` probably to encode/decode payload size. I should see if i can make it optional and make a feature that only requires it when `actix-multipart` is enabled too.

**Comment by ghost** [comment]
> Oops, sorry! It's been a while since I've used GitHub for code review.

Haha, No worries, shit happens ^^

**Comment by ghost** [comment]
There we go, that should do it. 
- Feature gate for actix-multipart and any transitive dependencies that may need pinning
- feature-gated docs
- running tests both with and without `--all-tests` flag in CI

**Comment by ghost** [comment]
And the requested examples. I also made sure to at least compile the examples, since a non-compiling example isn't a very good example.

File: Cargo.toml [hunk 3]
```diff
@@ -11,23 +11,39 @@ keywords = ["actix", "middleware", "csrf"]
...
-# These versions are pinned to ensure compatibility with 4.0.0
 anyhow = "1"
 actix-web = { version = "=4.3.1", features = [ "cookies", "openssl"] }
 actix-http = "=3.3.1"
 serde = { version = "1", features = [ "derive" ] }
 tokio = { version = "1", features = [ "macros", "rt-multi-thread" ] }
 openssl = { version = "0.10" }
+mime = "0.3.17"
+actix-multipart = { version = "0.7.2" }
+parse-size = { version = "=1.0.0"}
```
Comment (siblingsofthevoid) [inline Cargo.toml:41]: these are here for the examples. `dev-dependencies` cannot be optional, but are luckily not really used anywhere within the library.

Comment (siblingsofthevoid) [inline Cargo.toml:41]: these are here for the examples. `dev-dependencies` cannot be optional, but are luckily not really used anywhere within the library.

File: Cargo.toml [hunk 4]
```diff
@@ -11,23 +11,39 @@ keywords = ["actix", "middleware", "csrf"]
...
 cookie = "0.16"
 rand = { version = "0.8", features = [ "std_rng" ] }
 tracing = "0.1"
 serde = { version = "1", default-features = false }
+actix-multipart = { version = "0.7.2" , optional = true }
+# Needs pinning cuz MSRV for versions > 1.1.0 is rust 1.82
+parse-size = { version = "=1.0.0", optional = true }
 
 [dev-dependencies]
-# These versions are pinned to ensure compatibility with 4.0.0
```
Comment (ghost) [inline Cargo.toml:23]: This didn't really seem necessary anymore since actix is now pinned to `4.3.1`

**Review by ghost — COMMENTED** [review]
The example itself is just a modified copy of the `form_token` example, since most of the code is just the same. As usual, just tell me if there are any issues with the changes made. As far as i can tell that should also be all the requested changes plus a few minor things i could think of along the way ^^

**Comment by ghost** [comment]
Seems that actually wasn't needed. Idk why nvim complained about it not being there... oh well, now it's clean

File: src/lib.rs [hunk 5]
```diff
@@ -34,8 +34,13 @@
...
 //! ## Features:
-//! - `actix-multipart` Enables compatibility with
-//!     the [`actix_multipart`] library.
+#![cfg_attr(
+    feature = "actix-multipart",
+    doc = r##"
+- `actix-multipart` Enables compatibility with
+    the [`actix_multipart`] library.
+"##
+)]
```
Comment (edward-shen) [inline src/lib.rs]: Feature visibility wise, wouldn't it be better to keep this ungated, so people without the feature can find it and add it in? Otherwise it's a little more difficult to find the feature.

I'm ok either way -- just wanted to hear your thoughts on that

**Review by edward-shen — APPROVED** [review]
Just let me know what you think about the last comment I made. If you disagree, I'll merge as-is.

Thanks again for your contributions! I know this went from a small technical addition to much more doc work, but it really goes a long way so I definitely recognize the hard work here!

File: src/lib.rs (hunk 5 above)
Comment (edward-shen) [reply src/lib.rs]: Ah, I guess on docs.rs all features are set. Is this for offline doc usage then?

What do you think about this then?

```diff
diff --git a/src/lib.rs b/src/lib.rs
index dfa8dab..f339898 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -34,6 +34,13 @@
 //! render all CSRF mitigation techniques ineffective!
 //!
 //! ## Features:
+#![cfg_attr(
+    not(feature = "actix-multipart"),
+    doc = r##"
+- `actix-multipart` Enables compatibility with
+    the [`actix_multipart`] library. (Not currently enabled)
+"##
+)]
 #![cfg_attr(
     feature = "actix-multipart",
     doc = r##"
```

File: examples/file_upload_form.rs [hunk 6]
```diff
@@ -0,0 +1,113 @@
...
+    images: Vec<TempFile>,
+}
+
+impl CsrfGuarded for UploadForm {
+    fn csrf_token(&self) -> &CsrfToken {
+        &self.csrf_token
+    }
+}
+
+/// Validates an uload form that has a CSRF token.
```
Comment (edward-shen) [inline examples/file_upload_form.rs]:
```suggestion
/// Validates an upload form that has a CSRF token.
```

Comment (ghost) [reply examples/file_upload_form.rs]: oops, I'll go and have a look at all the stuff again and see if there are more spelling mistakes ^^

File: src/lib.rs (hunk 5 above)
Comment (ghost) [reply src/lib.rs]: Ah yeah no this won't work. Notice how the last `actix-multipart` is a doc link. This will only work if we feature gate it, since the dependency doesn't exist if the feature isn't enabled.

In that case We'd have to manually maintain that link and upxate it when needed... or have it not be a link.

**Comment by ghost** [comment]
> Thanks again for your contributions! 

Gladly. Gotta use my experience somewhere ^^

> I know this went from a small technical addition to much more doc work, but it really goes a long way so I definitely recognize the hard work here!

No worries, Documentation is half the work and bad documentation Is worse than none at all.

File: src/lib.rs (hunk 5 above)
Comment (edward-shen) [reply src/lib.rs]: Hmm, I'll leave it to your discretion on what you want to do here!

Comment (ghost) [reply src/lib.rs]: I decided to remove the feature-gate and the link, since that makes the list more easy to use offline.

**Comment by edward-shen** [comment]
Last changes look good to me! Thanks again for your contributions.
